name: plushie_daycare_flutter
description: "A pet care simulation"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  auto_route: ^9.2.2
  flame: ^1.35.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  shared_preferences: ^2.5.3

dev_dependencies:
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/images/
  - assets/images/andrew_sprite.png
  - assets/images/chilli_sprite.png

  fonts:
    - family: SourGummy
      fonts:
        - asset: fonts/SourGummy-VariableFont_wdth_wght.ttf
        - asset: fonts/SourGummy-Italic-VariableFont_wdth,wght.ttf
          style: italic
